// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserRequest
	UserMessage
	UserCreated
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRequest struct {
	Ghubid int32  `protobuf:"varint,1,opt,name=ghubid" json:"ghubid,omitempty"`
	Id     int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Login  string `protobuf:"bytes,3,opt,name=login" json:"login,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto1.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserRequest) GetGhubid() int32 {
	if m != nil {
		return m.Ghubid
	}
	return 0
}

func (m *UserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type UserMessage struct {
	UserText string `protobuf:"bytes,1,opt,name=userText" json:"userText,omitempty"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto1.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserMessage) GetUserText() string {
	if m != nil {
		return m.UserText
	}
	return ""
}

type UserCreated struct {
	CreatedId int32 `protobuf:"varint,1,opt,name=createdId" json:"createdId,omitempty"`
}

func (m *UserCreated) Reset()                    { *m = UserCreated{} }
func (m *UserCreated) String() string            { return proto1.CompactTextString(m) }
func (*UserCreated) ProtoMessage()               {}
func (*UserCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserCreated) GetCreatedId() int32 {
	if m != nil {
		return m.CreatedId
	}
	return 0
}

func init() {
	proto1.RegisterType((*UserRequest)(nil), "proto.UserRequest")
	proto1.RegisterType((*UserMessage)(nil), "proto.UserMessage")
	proto1.RegisterType((*UserCreated)(nil), "proto.UserCreated")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserSvc service

type UserSvcClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserMessage, error)
	CreateUser(ctx context.Context, in *UserMessage, opts ...grpc.CallOption) (*UserCreated, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserMessage, error) {
	out := new(UserMessage)
	err := grpc.Invoke(ctx, "/proto.UserSvc/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) CreateUser(ctx context.Context, in *UserMessage, opts ...grpc.CallOption) (*UserCreated, error) {
	out := new(UserCreated)
	err := grpc.Invoke(ctx, "/proto.UserSvc/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserSvc service

type UserSvcServer interface {
	GetUser(context.Context, *UserRequest) (*UserMessage, error)
	CreateUser(context.Context, *UserMessage) (*UserCreated, error)
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSvc/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateUser(ctx, req.(*UserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserSvc_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserSvc_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto1.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xde, 0x5c, 0xdc, 0xa1, 0xc5,
	0xa9, 0x45, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x62, 0x5c, 0x6c, 0xe9, 0x19, 0xa5,
	0x49, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x10, 0x1f, 0x17, 0x53,
	0x66, 0x8a, 0x04, 0x13, 0x58, 0x8c, 0x29, 0x33, 0x45, 0x48, 0x84, 0x8b, 0x35, 0x27, 0x3f, 0x3d,
	0x33, 0x4f, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x51, 0xd2, 0x84, 0x18, 0xe6, 0x9b,
	0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x24, 0xc5, 0xc5, 0x01, 0xb2, 0x30, 0x24, 0xb5, 0xa2, 0x04,
	0x6c, 0x1c, 0x67, 0x10, 0x9c, 0xaf, 0xa4, 0x0d, 0x51, 0xea, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x9a,
	0x22, 0x24, 0xc3, 0xc5, 0x99, 0x0c, 0x61, 0x7a, 0xc2, 0xac, 0x46, 0x08, 0x18, 0x95, 0x71, 0xb1,
	0x83, 0x14, 0x07, 0x97, 0x25, 0x0b, 0x19, 0x73, 0xb1, 0xbb, 0xa7, 0x96, 0x80, 0x78, 0x42, 0x42,
	0x10, 0x9f, 0xe8, 0x21, 0xb9, 0x5f, 0x0a, 0x59, 0x0c, 0xea, 0x0c, 0x25, 0x06, 0x21, 0x33, 0x2e,
	0x2e, 0x88, 0x45, 0x18, 0xfa, 0xa0, 0x6a, 0x50, 0xf4, 0x41, 0xdd, 0xa4, 0xc4, 0x90, 0xc4, 0x06,
	0x16, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x9c, 0x3c, 0x4f, 0x38, 0x01, 0x00, 0x00,
}
